spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #设为 true 便开启通过注册中心的自动根据 `serviceId` 创建路由的功能
          enabled: true
      routes:
        - id: add_request_header_route
          uri: http://jarvan-iv.github.io/2019/10/02/spring%20cloud%E6%9C%8D%E5%8A%A1%E9%97%B4%E8%B0%83%E7%94%A8/
          predicates:
            - Path=/consumer/**
          #filters:
          #  - AddRequestHeader=X-Request-red, blue

        - id: time_after_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/after/**
            - After=2020-02-01T16:50:00+08:00[Asia/Shanghai]

        - id: time_before_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/before/**
            - Before=2020-02-01T18:00:00+08:00[Asia/Shanghai]

        - id: time_between_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/between/**
            - Between=2020-02-01T17:00:00+08:00[Asia/Shanghai], 2020-02-01T18:00:00+08:00[Asia/Shanghai]

        - id: cookie_route
          uri: http://www.ityouknow.com/
          predicates:
            - Cookie=chocolate, ch.p

        - id: header_route
          uri: http://www.ityouknow.com/
          predicates:
            - Header=X-Request-Id, \d+

        - id: host_route
          uri: http://www.ityouknow.com/
          predicates:
            - Host=**.somehost.org,**.anotherhost.org

        - id: method_route
          uri: http://www.ityouknow.com/
          predicates:
            - Method=POST

        - id: host_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/red/{segment},/blue/{segment}

        - id: query_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/query/**
            - Query=color, gree.

        - id: query_name_route
          uri: http://www.ityouknow.com/
          predicates:
            - Path=/query/**
            - Query=user

        - id: remoteaddr_route
          uri: https://example.org
          predicates:
            - RemoteAddr=192.168.1.1/24
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      # eureka-server地址
      defaultZone: http://127.0.0.1:8089/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug