---
spring:
  application:
    name: eureka-server
  profiles: node1
server:
  port: 8087
eureka:
  instance:
    hostname: node1
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    #register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    #fetch-registry: false
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://node2:8088/eureka/,http://node3:8089/eureka/
---
spring:
  application:
    name: eureka-server
  profiles: node2
server:
  port: 8088
eureka:
  instance:
    hostname: node2
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    #register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    #fetch-registry: false
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://node1:8087/eureka/,http://node3:8089/eureka/
---
spring:
  application:
    name: eureka-server
  profiles: node3
server:
  port: 8089
eureka:
  instance:
    hostname: node3
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    #register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    #fetch-registry: false
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://node1:8087/eureka/,http://node2:8088/eureka/
---